name = sundial
description = Adds a sundial, assumes shadow_sky_body_orbit_tilt = 45, other values may work.
optional_depends = basic_materials, dye
supported_games = *
author = The4spaceconstants
title = Sundial
